name: CI

on:
  push:
  pull_request:
  schedule: [cron: "20 5 * * *"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Build features-none
        run: cargo build --verbose
      - name: Build features-windows
        run: cargo build --verbose --features windows 
      - name: Build features-all
        run: cargo build --verbose --all-features
      - name: Build tests
        run: cargo test --verbose --all-features --no-run
      - name: Run tests
        run: cargo test --verbose --all-features
      - name: Clippy
        run: cargo clippy --all-features --tests --lib -- -W clippy::all
        env:
          RUSTFLAGS: -D warnings
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Set minimal versions
        run: cargo +nightly update -Z minimal-versions
      - name: Build tests (minimal versions)
        run: cargo +stable test --all-features --verbose --no-run
      - name: Run tests (minimal versions)
        run: cargo +stable test --all-features --verbose
